services:
  webapp:
    build: .
    ports:
      - "8080:5000"
    # This tells Compose to start the db before the webapp
    depends_on:
      - db

  db:
    # Use the official PostgreSQL image
    image: "postgres:13-alpine"
    # These are settings passed to the PostgreSQL container on startup
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase